name: build

on:
    schedule:
        - cron: "01 23 * * *"
    push:
        branches: [build]

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    ET_REPO_PATH: ${{ secrets.ET_REPO_PATH }}
    ET_REPO_TOKEN: ${{ secrets.ET_REPO_TOKEN }}

jobs:
    # =============== ODOO COMMUNITY ==================
    build-community:
        strategy:
            matrix:
                ref: [14, 15, 16, 17]
        permissions:
            contents: write
        uses: ./.github/workflows/build.yml
        with:
            ref: ${{ matrix.ref }}
            image_tag: odoo:${{ matrix.ref }}
            version_code: ${{ matrix.ref }}.0
        secrets: inherit

    # =============== ODOO ENTERPRISE ==================
    build-enterprise:
        needs: [build-community]
        strategy:
            matrix:
                ref: [14, 15, 16, 17]
                et_workspace_path: ["./et-addons"]
        uses: ./.github/workflows/build-et.yml
        with:
            ref: ${{ matrix.ref }}
            image_tag: odoo-et:${{ matrix.ref }}
            et_workspace_path: ${{ matrix.et_workspace_path }}
        secrets: inherit
